FROM openresty/openresty:alpine

RUN apk add --no-cache git perl curl
RUN opm get ledgetech/lua-resty-http
RUN luarocks install lua-cjson

# IF WANNA TRY BASIC AUTH - ENABLE AND DISABLE THE PLUGIN
# COPY src/basic_auth.lua /usr/local/openresty/nginx/conf/basic_auth.lua

COPY src/resty dest
WORKDIR 