services:
  registry:
    image: distribution/distribution:edge
    ports:
      - "5001:5000"
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"  # Enable l'eliminazione
    volumes:
      - registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/configs/config.yml 