FROM alpine:latest AS builder

RUN apk add --no-cache lua5.1-dev lua5.1 gcc musl-dev openssl openssl-dev git curl unzip luarocks

COPY . /tmp/plugins/
WORKDIR /tmp/plugins/src/resty/opa_auth

# Needed only if we have dep folder with some dependencies
#RUN for dep in deps/*; do cd $dep; luarocks make --pack-binary-rock; cd -; done;
RUN luarocks make --pack-binary-rock --deps-mode=none

RUN mkdir /prebuilt-rocks
RUN find . -name '*.rock' | xargs -I {} mv {} /prebuilt-rocks

FROM openresty/openresty:alpine

RUN apk add --no-cache git perl curl unzip
RUN opm get ledgetech/lua-resty-http
RUN luarocks install lua-cjson

COPY --from=builder /prebuilt-rocks /prebuilt-rocks/

RUN luarocks install /prebuilt-rocks/opa_auth*.rock
