version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
storage:
  s3:
    accesskey: minioadmin
    secretkey: minioadmin
    region: us-east-1
    regionendpoint: http://minio1:9000
    bucket: registry-bucket
    encrypt: false
    secure: false
    v4auth: true
    chunksize: 5242880
    forcepathstyle: true
    rootdirectory: /registry-bucket/data
http:
  addr: localhost:5000
  secret: aRandomSecret
  # tls:
  #   certificate: /certs/fullchain.pem
  #   key: /certs/privkey.pem
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3